[CmdletBinding()]
param(
    [string]$Root = '',
    [string]$BuildDirectory = '',
    [ValidateSet('light', 'dark', 'high_contrast')]
    [string[]]$Themes = @('light', 'dark', 'high_contrast')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# CP33: $PSScriptRoot can be empty when this script is invoked through a
# shell that doesn't preserve the launch context (notably Git Bash +
# powershell.exe -File). Resolve the script's own directory from
# $PSCommandPath (always populated when -File is used) and walk up two
# levels to the repo root.
$scriptDir = if (![string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    $PSScriptRoot
} elseif (![string]::IsNullOrWhiteSpace($PSCommandPath)) {
    Split-Path -Parent $PSCommandPath
} else {
    $PWD.Path
}
if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = (Resolve-Path (Join-Path $scriptDir '..\..')).Path
}

if ([string]::IsNullOrWhiteSpace($BuildDirectory)) {
    $BuildDirectory = Join-Path $Root 'out\build\x64-debug\Debug'
}
$BuildDirectory = [System.IO.Path]::GetFullPath($BuildDirectory)
$outputDirectory = Join-Path $Root 'docs\VISUAL_AUDIT'
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null

$auditExe = Join-Path $BuildDirectory 'NativeFrameUIVisualAudit.exe'
if (-not (Test-Path -LiteralPath $auditExe -PathType Leaf)) {
    throw "Visual-audit executable not found: $auditExe. Configure and build x64-debug with BUILD_TESTING=ON first."
}

$samples = @(
    [pscustomobject]@{ Name = 'Workbench';         Exe = 'NativeFrameUIWorkbench.exe' },
    [pscustomobject]@{ Name = 'Showcase';          Exe = 'NativeFrameUIShowcase.exe' },
    [pscustomobject]@{ Name = 'DarkStudio';        Exe = 'NativeFrameUIDarkStudio.exe' },
    [pscustomobject]@{ Name = 'SettingsDemo';      Exe = 'NativeFrameUISettingsDemo.exe' },
    [pscustomobject]@{ Name = 'DialogTour';        Exe = 'NativeFrameUIDialogTour.exe' },
    [pscustomobject]@{ Name = 'ResourceGallery';   Exe = 'NativeFrameUIResourceGallery.exe' },
    [pscustomobject]@{ Name = 'ComponentGallery';  Exe = 'NativeFrameUIComponentGallery.exe' },
    [pscustomobject]@{ Name = 'ThemeDemo';         Exe = 'NativeFrameUIThemeDemo.exe' },
    [pscustomobject]@{ Name = 'ControlsPlayground';Exe = 'NativeFrameUIControlsPlayground.exe' },
    [pscustomobject]@{ Name = 'Charts';            Exe = 'NativeFrameUICharts.exe' }
)

$results = [System.Collections.Generic.List[object]]::new()
foreach ($sample in $samples) {
    $sampleExe = Join-Path $BuildDirectory $sample.Exe
    foreach ($theme in $Themes) {
        $suffix = if ($theme -eq 'high_contrast') { 'hc' } else { $theme }
        $fileName = '{0}_{1}.png' -f $sample.Name, $suffix
        $outputPng = Join-Path $outputDirectory $fileName

        if (-not (Test-Path -LiteralPath $sampleExe -PathType Leaf)) {
            $results.Add([pscustomobject]@{
                Sample = $sample.Name; Theme = $theme; File = $fileName
                Status = "FAILED: sample executable not found: $sampleExe"
            })
            continue
        }

        Write-Host ("Capturing {0} [{1}]" -f $sample.Name, $theme)
        & $auditExe $sampleExe $theme $outputPng
        $exitCode = $LASTEXITCODE
        $status = if ($exitCode -eq 0 -and (Test-Path -LiteralPath $outputPng -PathType Leaf)) {
            'captured'
        } else {
            "FAILED: NativeFrameUIVisualAudit exit code $exitCode"
        }
        $results.Add([pscustomobject]@{
            Sample = $sample.Name; Theme = $theme; File = $fileName; Status = $status
        })
    }
}

$indexPath = Join-Path $outputDirectory 'INDEX.md'
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# NativeFrameUI Visual Audit Screenshots')
$lines.Add('')
$lines.Add('Generated by `tools/visual_audit/run_audit.ps1` using the native Win32 `PrintWindow` capture path and WIC PNG encoding.')
$lines.Add('')
$lines.Add('| Sample | Theme request | Screenshot | Status |')
$lines.Add('|---|---|---|---|')
foreach ($result in $results) {
    $relative = "docs/VISUAL_AUDIT/$($result.File)"
    $link = if ($result.Status -eq 'captured') { "[$($result.File)]($($result.File))" } else { '-' }
    $lines.Add("| $($result.Sample) | $($result.Theme) | $link | $($result.Status) |")
}
$lines.Add('')
$lines.Add('Note: most samples currently ignore the `--theme` launch request. The three captures remain intentional audit evidence; identical images expose missing runtime theme support rather than being synthesized theme variants.')
[System.IO.File]::WriteAllLines($indexPath, $lines, [System.Text.UTF8Encoding]::new($false))

$failures = @($results | Where-Object { $_.Status -ne 'captured' })
Write-Host "Visual-audit index: $indexPath"
if ($failures.Count -gt 0) {
    Write-Error "$($failures.Count) capture(s) failed. See INDEX.md for details."
    exit 1
}
Write-Host "Captured $($results.Count) native window screenshot(s)."
