name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: x64-debug
            os: windows-latest
            experimental: false
          - preset: x64-release
            os: windows-latest
            experimental: false
          - preset: arm64-debug
            os: windows-11-arm
            experimental: true
          - preset: clangcl-debug
            os: windows-latest
            cc: clangcl
            experimental: false
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}
      - name: Test
        run: ctest --preset ${{ matrix.preset }}
